function drawSigBar(ax,x1,x2,y,label)
plot(ax,[x1 x2],[y y],'k-','LineWidth',1.25);
text(ax,mean([x1 x2]),y + 0.012,label, ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','bottom', ...
    'FontSize',14, ...
    'FontWeight','bold');
end
